name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/himenon/pdf-crop-margins:latest,ghcr.io/himenon/pdf-crop-margins:${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
