name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: |
          pnpm build
          pnpm docker:build
          pnpm docker:push
        env:
          CI: true
          DOCKER_USER_NAME: ${{ github.actor }}
